# Generated by Django 4.2.29 on 2026-03-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_age_group_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='search_keywords',
            field=models.CharField(blank=True, help_text="Comma separated keywords for search (e.g. 'jawellery, jewelry')", max_length=255),
        ),
    ]
